### ISSUE TITLE
CS241 factual error: NULL value

### ISSUE THREAD

**Issue by matthew-robertson** [christhomson/lecture-notes#26]
On page 79 of the notes, sect 12.2.1, you say that instead of zero, one should choose a value that "that is not a power of four". In actuality, I imagine you meant that it should not be a multiple of four.

**Comment by christhomson** [comment]
Hey, thanks for letting me know! It's fixed now (d23c9bde7421a10e526545b3c4325fc7580ca67f). :smiley:
